- id: 1
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://scatterp:magic123@94.237.85.20:8332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 2
  key: litecoin
  code: ltc
  symbol: $
  coin: true
  quick_withdraw_max: 0
  rpc: http://scatterp:magic123@94.237.85.20:9335
  blockchain: https://live.blockcypher.com/ltc/tx/#{txid}
  address_url: https://live.blockcypher.com/ltc/address/#{address}
  assets:
  accounts:
    -
      address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 3
  key: ether
  code: eth
  symbol: $
  coin: true
  quick_withdraw_max: 0
  rpc: http://94.237.85.20:8545
  blockchain: https://live.blockcypher.com/ltc/tx/#{txid}
  address_url: https://live.blockcypher.com/ltc/address/#{address}
  assets:
  accounts:
# password db=*?D4L?d , address : b96b2aa33b3f88f20613cdfaa5c97e29f725d345
    -
      address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 4
  key: stellarcoin
  code: xlm
  symbol: " $  "
  coin: true
  quick_withdraw_max: 0
  rpc:  http://scatterp:magic123@94.237.85.20:5555
  blockchain: https://stellarchain.io/tx/#{txid}
  address_url: https://stellarchain.io/address/#{address}
  assets:
  accounts:
    -
      address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3

